version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: database_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
